# Generated by Django 5.2 on 2025-07-14 07:36

import mailer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='bcc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=mailer.models.pdf_file_path),
        ),
    ]
